name: valdeglace
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  simple_coverflow: '^0.0.6'
  transparent_image: '^0.1.0'
  url_launcher: "^3.0.1"
  share: "^0.4.0"

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
